### ISSUE TITLE
Add PR Template

### ISSUE THREAD

**Issue by Sriparno08** [sahil-sagwekar2652/GitHub-Automation-scripts#109]
**Issue Description:**

Add a PR template to the repository to make the PR opening process easier for contributors.

**Additional Information:**

I want to contribute as part of GSSoC'23.

**Labels:**
[Add appropriate labels to categorize the issue, such as bug, enhancement, documentation, etc.]

documentation

**Comment by bhavya1857** [comment]
HI could you assign me this issue as i am really good at writing

**Comment by palak-b19** [comment]
HI could you assign me this issue
