### ISSUE TITLE
Write a Installation script for the project.

### ISSUE THREAD

**Issue by sahil-sagwekar2652** [sahil-sagwekar2652/GitHub-Automation-scripts#11]
Write an installation script using bash to enable a single-line install for users, without having to manually clone the repository.
Here is a [reference](https://github.com/proffapt/code-runner)

**Comment by shubham-deshmukh** [comment]
Hi @sahil-sagwekar2652. I would like to work on this issue as a GSSOC'23 participant. Can you please assign it to me?

**Comment by i-am-yuvi** [comment]
Hey @sahil-sagwekar2652 I would like to work on it as GSSoC 23 participant

**Comment by SaarthakMaini** [comment]
Hey @sahil-sagwekar2652 ,

I am currently participating in GSSoC 2023 and would like to contribute to the issue

Thank you!

**Comment by VardaPanchal005** [comment]
I would like to would like to work on the the issue.

**Comment by sahil-sagwekar2652** [comment]
Hey everyone, the issues are being assigned on a first-come-first-serve basis. In the meanwhile, check out the other issues, or feel free to create your own. Also, don't make a PR without raising an issue and getting it assigned to you. If the original assigned isn't active or not working on the issue, then I'll assign it to the next contributor. 

One contributor will be assigned to one issue at a time, so please take up one issue at a time, don't comment on every issue.
