### ISSUE TITLE
GitHub action to automatically add contributor name

### ISSUE THREAD

**Issue by Soumya1219** [sahil-sagwekar2652/GitHub-Automation-scripts#112]
**Issue Description:**
This GitHub action is used to directly add contributor name after successfully the request is merged. 

**Expected Behavior:**
The contributor name will automatically gets add with the help of addition of .yml file in GitHub workflow. 

**Current Behavior:**

**Additional Information:**

**Labels:**
Enhancement

**Comment by sahil-sagwekar2652** [comment]
The contributors are already being updated through the API. Check the last part of the README file. If you have any new ideas or wish to propose any changes, feel free to create a new issue.
