### ISSUE TITLE
Forgot to mention the weblink to this project to view it as a website in README.md

### ISSUE THREAD

**Issue by bhavya1857** [sahil-sagwekar2652/GitHub-Automation-scripts#117]
**Issue Description:**
Nothing much just the maintainer has forgotten to display his website to see of how the project works.

**Expected Behavior:**
[Describe what should happen when the issue is resolved or the feature is implemented.] Everyone can view it as in the form of website, many didn't know the graphics folder were having pics for the website.

**Current Behavior:**
[Describe the current behaviour or any error messages encountered, if applicable.] Its just a github project, but if implemented we can see it as a website.

**Labels:**
documentation

**Comment by Shatakshi0** [comment]
I would like to work on this issue under gssoc'23

**Comment by sahil-sagwekar2652** [comment]
The website is already deployed on GitHub pages, which can be seen in the environments section on the home page of the repository.
