### ISSUE TITLE
Improving the readme file 

### ISSUE THREAD

**Issue by harshsingh32** [sahil-sagwekar2652/GitHub-Automation-scripts#17]
I would like to improve the readme file of this project, making it more expressive and engaging for the users.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by MeMeee1** [comment]
Hello 😃 

I would like to take on this issue and work on improving the readme file under GSSoC'23. I believe a well-written and informative readme is crucial for the project's success. I'll start by reviewing the existing content, adding relevant sections, enhancing clarity, and incorporating any missing information. 

If there are any specific requirements or suggestions for the readme, please let me know. I'll ensure that the readme is comprehensive, easy to understand, and helps users get started with the project smoothly.

Looking forward to contributing to the project!

**Comment by bakhtawarkhansafi** [comment]
I'm interested to contribute this project

**Comment by sahil-sagwekar2652** [comment]
Hey everyone, the issues are being assigned on a first-come-first-serve basis. In the meanwhile, check out the other issues, or feel free to create your own. Also, don't make a PR without raising an issue and getting it assigned to you. If the original assigned isn't active or not working on the issue, then I'll assign it to the next contributor.

One contributor will be assigned to one issue at a time, so please take up one issue at a time, don't comment on every issue.
