### ISSUE TITLE
Bash Script: Create a new repository on GitHub

### ISSUE THREAD

**Issue by iamthecloverly** [sahil-sagwekar2652/GitHub-Automation-scripts#23]
Description:
I am an active participant of the GirlScript Summer of Code (GSSoC) program and I would like to contribute to this issue. I believe it aligns well with my skills and interests.

Expected Outcome:
By assigning this issue to me, I aim to contribute my expertise and knowledge towards resolving the problem or implementing the requested feature effectively and efficiently.

Reason for Requesting Assignment:
As a GSSoC contributor, I am committed to actively contributing to open-source projects. This issue presents an opportunity for me to showcase my skills, learn from the experience, and contribute meaningfully to the project.

Thank you for considering my request. I look forward to working on this issue and making a positive impact on the project.

**Comment by bshantherishenoy** [comment]
hello sir I'm GSSOC23 contributor can you assign me this issue i would like to explore and resolve it.
Its quite more easier to do it in bash as commands of git work here to for creating a repo a curl post would go good

**Comment by sahil-sagwekar2652** [comment]
Hello everyone, thank you for your interest in this project.

@iamthecloverly I am assigning this issue to you now, you can start working on it. @bshantherishenoy I could assign the same issue to two people at a time but the GSSoC'23 admins have told us to assign issues on a first-come-first-serve basis. I would suggest you create a new issue or if the original assigned is inactive then I'll be able to assign it to you.

@anupammaurya6767 I really appreciate your prompt efforts but please avoid creating pull requests for issues which aren't assigned to you. I am sorry for the inconvenience, the program managers will soon create a discord channel for this project, and we will discuss all the issues and progress over there. For now, don't delete your PR, if the above contributors don't work on them, then I'll assign it to you.

**Comment by iamthecloverly** [comment]
> Hello everyone, thank you for your interest in this project.
> 
> @iamthecloverly I am assigning this issue to you now, you can start working on it. @bshantherishenoy I could assign the same issue to two people at a time but the GSSoC'23 admins have told us to assign issues on a first-come-first-serve basis. I would suggest you create a new issue or if the original assigned is inactive then I'll be able to assign it to you.
> 
> @anupammaurya6767 I really appreciate your prompt efforts but please avoid creating pull requests for issues which aren't assigned to you. I am sorry for the inconvenience, the program managers will soon create a discord channel for this project, and we will discuss all the issues and progress over there. For now, don't delete your PR, if the above contributors don't work on them, then I'll assign it to you.

Thank you, Will start contributing from now!
