### ISSUE TITLE
Write a 'push_repo' script

### ISSUE THREAD

**Issue by sahil-sagwekar2652** [sahil-sagwekar2652/GitHub-Automation-scripts#3]
This script will initialize and push an existing local repository to a newly created remote repository of the same name.

**Comment by shubham-deshmukh** [comment]
Hi @sahil-sagwekar2652. I would like to work on this issue as a GSSOC'23 participant. Can you please assign it to me?

**Comment by sahil-sagwekar2652** [comment]
Hello @shubham-deshmukh , thank you for showing interest in this project. You can join our slack server for further discussions -
https://join.slack.com/t/githubautomat-9t49360/shared_invite/zt-1v05p5kao-UBmelVfZd6EBjGuzd_6XYg

**Comment by ashvaneetk** [comment]
Hey @sahil-sagwekar2652 assign me this issue.
I can make changes so that the script takes the --path argument, which represents the path to the existing local repository. It initializes the local repository, creates a new remote repository with the same name, and pushes the changes to the remote repository.

**Comment by ganeshrevadi** [comment]
@sahil-sagwekar2652 Does this involve writing a python script using selenium for pushing local file's to a remote github repo?

**Comment by sahil-sagwekar2652** [comment]
Hey everyone, great to see you all here.
The program managers for GSSoC'23 will be creating discord channels for each project.
So we will eventually have to move out discussions to the GSSoC discord server. Also, we haven't received any information about how we are going to track the contributions,
so till then I won't be able to merge your PRs. And just a quick reminder - We are all here to learn and grow so don't try to rush anything, let us discuss the ideas, take inputs and
then start the actual coding. Cutting with a sharpened axe is much easier.

**Comment by VardaPanchal005** [comment]
I would like to work on the issue

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by sahil-sagwekar2652** [comment]
Hey everyone, the issues are being assigned on a first-come-first-serve basis. In the meanwhile, checkout the other issues, or feel free to create your own. Also, don't make a PR without raising an issue and getting it assigned to you.

**Comment by shubham-deshmukh** [comment]
@sahil-sagwekar2652 Thank you for assigning me this task/issue.

**Comment by shubham-deshmukh** [comment]
Hey @sahil-sagwekar2652 
I want to provide an update on the task/issue #3.
As per my understanding, 
the ask is ```Initialize and push an existing local repository to a newly created remote repository of the same name. ```

> Objective:
> 1. Initialize the directory as local repo if it does not exist
> 2. Push the local repository to the newly created remote repository

## Algorithm:

Arguments: {path of the directory, URL of newly created remote repo of the same name}

1. Validate Arguments : 
    1. If an invalid directory path
            1. print (error)
	    2. exit
    1. If an invalid remote repo URL 
            1. print (error)
            2. exit
    1. If inconsistency with the local repo name with the newly created remote repo name
            1. print (error)
            2. exit
1. If not a local repo 
    1. initialize the directory as local repo
1. Push the existing local repo (including all branches, tags, etc.) to the newly created remote repo.
***
Please provide your valuable feedback including other contributors.
