### ISSUE TITLE
[GSSOC'23] Write a 'create_branch' script

### ISSUE THREAD

**Issue by Daksh-Goel12** [sahil-sagwekar2652/GitHub-Automation-scripts#31]
Hi @sahil-sagwekar2652 I am GSSoc'23 conributor,. I would like to add the create_branch script to this project. Please assign this issue to me.

**Comment by Akshayp02** [comment]
hello sir i would like to contribute this project under GSSoc23 so can you assign me this isshu

**Comment by Daksh-Goel12** [comment]
@Akshayp02 I already opened this issue. The right way to go about this is to open an issue to fix a different problem and not the one I highlighted.

**Comment by sahil-sagwekar2652** [comment]
That's a great idea, you can work on this issue now @Daksh-Goel12
