### ISSUE TITLE
add switching branch script

### ISSUE THREAD

**Issue by Soumyajit2825** [sahil-sagwekar2652/GitHub-Automation-scripts#35]
I want to try to create a script that will switch between branches of any repository

**Comment by sahil-sagwekar2652** [comment]
Hello @Soumyajit2825  , hope you are doing well.

Switching branches is only one command "git checkout <branch_name>". I don't think that should require any extra scripting. If you have any other idea please feel free to raise another issue. Closing this issue for now.
