### ISSUE TITLE
#GSSoC2023 Create a requirements.txt file

### ISSUE THREAD

**Issue by Grogu22** [sahil-sagwekar2652/GitHub-Automation-scripts#36]
As this is a python project, we need to create a requirements.txt file to avoid future dependency conflicts.
So, to install dependencies we can just :
`$ pip install -r requirements.txt`

_Cannot assign labels , hence the #GSSoC'23_  😢

**Comment by Grogu22** [comment]
@sahil-sagwekar2652 please assign it to me

**Comment by sahil-sagwekar2652** [comment]
Hello @Grogu22 , hope you are doing well.

Assuming you have gone through the README and CONTRIBUTING.md, you might have overlooked that project does not have any external dependencies as of now. If you have any other idea please feel free to raise another issue. Closing this issue for now.
