### ISSUE TITLE
Creating branch on a repo 

### ISSUE THREAD

**Issue by CS50X-RGB** [sahil-sagwekar2652/GitHub-Automation-scripts#38]
We can use the subprocess()  which consists of subprocess.run() to run the command inside of the run() in my python script.

**Comment by CS50X-RGB** [comment]
@sahil-sagwekar2652 I would like to work on this issue.

**Comment by CS50X-RGB** [comment]
@sahil-sagwekar2652 I would like to work on this issue.

**Comment by CS50X-RGB** [comment]
@sahil-sagwekar2652 I would like to work on this issue.

**Comment by CS50X-RGB** [comment]
@sahil-sagwekar2652 I would like to work on this issue.

**Comment by danascape** [comment]
This is something that is required since the default branch is hard coded in the script

https://github.com/sahil-sagwekar2652/GitHub-Automation-scripts/blob/main/scripts/create_repo#L32

**Comment by CS50X-RGB** [comment]
> This is something that is required since the default branch is hard coded in the script
> 
> https://github.com/sahil-sagwekar2652/GitHub-Automation-scripts/blob/main/scripts/create_repo#L32

Yupp we can add this  piece of code in this flow aur we can create a bash script for it

**Comment by CS50X-RGB** [comment]
Using bash will be more I guess.

**Comment by danascape** [comment]
Well, the main script doesn't have much of a usecase, so adding another script to support it is not required

**Comment by CS50X-RGB** [comment]
@sahil-sagwekar2652 any update?

**Comment by sahil-sagwekar2652** [comment]
Is there really a need for a script for this? we just have 1 command 'git branch'

**Comment by CS50X-RGB** [comment]
> Is there really a need for a script for this? we just have 1 command 'git branch'

Okay
