### ISSUE TITLE
Creating back to top for the read me file.

### ISSUE THREAD

**Issue by karthikbhandary2** [sahil-sagwekar2652/GitHub-Automation-scripts#40]
Hello @sahil-sagwekar2652 please assign me to this issue.

**Comment by danascape** [comment]
This doesn't make any sense.
Think of something more. And improving the readme is also mentioned in other issues.
Do not force try to create something unnecessary.

https://github.com/sahil-sagwekar2652/GitHub-Automation-scripts/issues/17

**Comment by danascape** [comment]
https://github.com/sahil-sagwekar2652/GitHub-Automation-scripts/issues/21

**Comment by karthikbhandary2** [comment]
are you a gssoc contributor? @danascape

**Comment by danascape** [comment]
> are you a gssoc contributor? @danascape

I am not a gssoc contributor but more of an open-source enthusiast and a passer by who saw this repo, who cares looking at a CONTRIBUTING.md and other issues before creating another issue

**Comment by tesla59** [comment]
Redundant issue
There is a lot more to do in this repo than just the readme file. If u just want to commit to readme then it's better u invest your time in learning the skill rather than wasting your time in this

**Comment by karthikbhandary2** [comment]
> > are you a gssoc contributor? @danascape
> 
> I am not a gssoc contributor but more of an open-source enthusiast and a passer by who saw this repo, who cares looking at a CONTRIBUTING.md and other issues before creating another issue

ok man what ever u say

**Comment by sahil-sagwekar2652** [comment]
Hey there @karthikbhandary2 , this is a very small improvement and does not need a lot of work, if you have any more ideas in mind, write them briefly in a new issue, closing this one.

**Comment by karthikbhandary2** [comment]
@sahil-sagwekar2652 ok understood
