### ISSUE TITLE
[GSSOC'23] Create simple UI to show the links to the scripts

### ISSUE THREAD

**Issue by TunrayoIlawole** [sahil-sagwekar2652/GitHub-Automation-scripts#42]
I would like to create a simple user interface to view all the links to the scripts in a card format. When a user clicks on the "create_repo" link for example, they will be navigated to the respective script. This user interface can be deployed using Netlify.

I am a GSSoC'23 contributor and would like to work on this if that is okay.
Thank you

**Comment by danascape** [comment]
There is no usecase for this though
