### ISSUE TITLE
Frontend: create a web page for the project

### ISSUE THREAD

**Issue by sahil-sagwekar2652** [sahil-sagwekar2652/GitHub-Automation-scripts#48]
If anyone is interested in designing a web page to display information about this project and the various scripts, they can take up this issue. Please go through the contributing guidelines before starting development.

**Comment by yyuvraj54** [comment]
please assign this task to me under gssoc23

**Comment by ashvaneetk** [comment]
hey @sahil-sagwekar2652 assign me this issue.
i can create web page to display information about this project and the various scripts keeping the desired layout.

**Comment by yyuvraj54** [comment]
ok i am working on it

**Comment by yyuvraj54** [comment]
i have almost created the web page plz tell me how would i share the code with you ??
or i should merge the code in this project (i have used html css and javascript also some tailwind css)

**Comment by sahil-sagwekar2652** [comment]
Hey there @yyuvraj54 , hope you are doing well. 

You can make a pull request to push your commits. Don't forget to reference this issue when making a PR.

**Comment by yyuvraj54** [comment]
ok
