### ISSUE TITLE
Add Shell Script for Adding New Files or Folder to GitHub Repository

### ISSUE THREAD

**Issue by VipulChauhan89** [sahil-sagwekar2652/GitHub-Automation-scripts#56]
### 
This feature introduces a convenient shell script that automates the process of adding new files to a GitHub repository. With this script, users can easily add files to their repository without manually performing the Git commands.
### Key Functionality of the Shell Script
The script clones the repository, copies the specified file to the repository directory, stages and commits the changes with a customizable commit message, pushes the changes to the repository, and then cleans up the temporary repository directory.

### Enhancing Efficiency in Managing GitHub Repositories
By providing a user-friendly and streamlined workflow, this feature enhances the efficiency of managing GitHub repositories. It reduces the manual effort required to add files, especially for users who frequently add new content to their projects.
### Improving Developer Experience with Effortless File Incorporation
This feature improves the overall developer experience and encourages users to engage more actively with their repositories, enabling them to quickly and effortlessly incorporate new files into their projects.

**Comment by sahil-sagwekar2652** [comment]
> The script clones the repository, copies the specified file to the repository directory, stages and commits the changes with a customizable commit message, pushes the changes to the repository, and then cleans up the temporary repository directory.

From what the issue title says, adding a new file can be achieved by 'git add'
I don't seem to get what the idea is. I'm sorry for my naivety. It would be really helpful if you could elaborate more.

**Comment by VipulChauhan89** [comment]
I want to say that adding files from the workspace to the staging area and then to the local repository and after that to the GitHub global repository.

As the script will clones the repository, copy the specified file to the repository directory, stage and commits the changes with a customizable commit message, push the changes to the repository, and then clean up the temporary repository directory.

As the user has to manually type 
```git 
git clone <url>
git add .
git commit -m "Commit Message"
git push -u origin main
```

**Comment by sahil-sagwekar2652** [comment]
I'm assigning this issue to you. Try to solve the problem so that the URL and commit message as well as the files to be staged can be chosen by the end user.
