### ISSUE TITLE
Create an Issue by Python

### ISSUE THREAD

**Issue by ayush-09** [sahil-sagwekar2652/GitHub-Automation-scripts#58]
To create an issue on GitHub using Python, you can utilize the GitHub API and the requests library.

This is the python script which utilize the GitHub API and create the issue with the relavant title and description.
Just run the python file with the required changes accordingly to your need.

**Comment by ayush-09** [comment]
I am an active participant of the GirlScript Summer of Code (GSSoC) program and I would like to contribute to this issue. I believe it aligns well with my skills and interests.
@sahil-sagwekar2652 Please assign this to me

**Comment by sahil-sagwekar2652** [comment]
This sounds like a good idea. I'm assigning this issue to you.

**Comment by ayush-09** [comment]
@sahil-sagwekar2652 Please review this issue and let me know if any changes required.
Thanks

**Comment by ayush-09** [comment]
@sahil-sagwekar2652 Thanks for review my code and tell my mistakes.
Apology for this error with the file name and code.
I miss the token part in that code now i update the code and its working fine with this
headers = {
    'Authorization': f'token {token}',
    'Accept': 'application/vnd.github.v3+json'
}
Please review this final code

**Comment by ayush-09** [comment]
@sahil-sagwekar2652 I updated this, please review and merge if everything is all right.
Thanks

**Comment by ayush-09** [comment]
@sahil-sagwekar2652 Please check this provide the relevant tag.
Thanks
