### ISSUE TITLE
grammatical error in CONTRIBUTING.md documentation.

### ISSUE THREAD

**Issue by RudrakshAtGithub** [sahil-sagwekar2652/GitHub-Automation-scripts#60]
**Issue Description:**
There are some grammatical errors in [CONTRIBUTING.md](https://github.com/sahil-sagwekar2652/GitHub-Automation-scripts/commit/a3e0882d6c97158766ca56d417f767b2ca533177).

**Expected Behavior:**
1) Remove "then".
2) Replace "the your" with "your".

**Current Behavior:**
1) ![Screenshot from 2023-05-24 23-25-48](https://github.com/sahil-sagwekar2652/GitHub-Automation-scripts/assets/119342758/6cccf21e-7f98-43c1-af13-bc783ed02423)
2) ![Screenshot from 2023-05-24 23-25-28](https://github.com/sahil-sagwekar2652/GitHub-Automation-scripts/assets/119342758/92b061ec-a9c0-41e9-87ce-ca8891068411)

**Label**:
documentation

**Comment by RudrakshAtGithub** [comment]
I am GSSoC'23 contributor,kindly assign this issue to me,would be glad to solve it.

**Comment by Eiman-Zulfiqar** [comment]
Hey, I do like to contribute. Assign me this task under label GSS0C23

**Comment by sahil-sagwekar2652** [comment]
Please try to add the installation command in the README as referenced here - https://github.com/sahil-sagwekar2652/GitHub-Automation-scripts/pull/18/commits/3f1023c40d4f71cfd862e44dea423290aaaff0ad

**Comment by RudrakshAtGithub** [comment]
> Please try to add the installation command in the README as referenced here - [3f1023c](https://github.com/sahil-sagwekar2652/GitHub-Automation-scripts/commit/3f1023c40d4f71cfd862e44dea423290aaaff0ad)

Can you elaborate the above,because Steps to installation are given with commands.
Tried ,but can't understand,please guide.

**Comment by sahil-sagwekar2652** [comment]
Check the commit which I have mentioned
The changes which the commit made have been overwritten due to my negligence, so I'm asking you to add the code again in the readme file. Add only the lines highlighted in green. Commit these new changes to the same branch with which you have made the PR.

**Comment by RudrakshAtGithub** [comment]
What I have understood is to delete all other lines except these green lines in README file
![image](https://github.com/sahil-sagwekar2652/GitHub-Automation-scripts/assets/119342758/a561deab-305b-4cfb-9b13-1c1e150a6f2e)

**Comment by Mimi97-aqua** [comment]
Hi
I would like to work on this. Please can you assign it to me?
