### ISSUE TITLE
[GSSOC'23] Documentation for create_repo.py file

### ISSUE THREAD

**Issue by SwastikGorai** [sahil-sagwekar2652/GitHub-Automation-scripts#62]
I'd like to write the documentation for the `create_repo.py` file. @sahil-sagwekar2652 , please assign this issue to me under GSSOC'23.

**Comment by Eiman-Zulfiqar** [comment]
Hi I do like to contribute. Assign me this issue under label GSSoC23.

**Comment by sahil-sagwekar2652** [comment]
Hey there @SwastikGorai . Could you elaborate a bit more about what changes you are proposing?

**Comment by SwastikGorai** [comment]
I'll write the docs for the code. Like, what exactly the lines do and why are those needed.
