### ISSUE TITLE
Add black linter workflow

### ISSUE THREAD

**Issue by metabiswadeep** [sahil-sagwekar2652/GitHub-Automation-scripts#87]
**Issue Description:**
Add a suitable linter to ensure proper linting of the code. As a project with multiple users contributing to it, it is essential to maintain a proper linting style to ensure better code readability by users. An excellent way to do this is by automatic linting checks using GitHub actions.

I would like to work on this project as a part of GSSoC 23. Please assign this issue to me.

**Expected Behavior:**
Linter will run on every push and on every pull request.

**Current Behavior:**
None

**Labels:**
enhancement

**Comment by metabiswadeep** [comment]
Please assign this issue to me @sahil-sagwekar2652

**Comment by metabiswadeep** [comment]
@sahil-sagwekar2652 Could you assign this issue to me?

**Comment by Priyank-Vaidya** [comment]
I would like to work under this issue under GSSOC'23
