### ISSUE TITLE
Feat: Create multiple repos from a template repo.

### ISSUE THREAD

**Issue by RAOdotSH** [sahil-sagwekar2652/GitHub-Automation-scripts#94]
**Issue Description:**
Generating large number of repos for each individual/participant(each repo will have unique suffix) from a template repo. Add specific contributors to particular repo. 

**Expected Behavior:**
It would automate a huge tedious task of creating multiple repos of same content but for different contributors/individuals. This is will help in diffeent types of coding competitions. It was implemented by Sahaj Software Solutions in their recent campus hackathons. 

**Current Behavior:**
- -

**Additional Information:**
It will require a json file which consists of participant name as key and an array of contributors to be added to that participant's repo as value.

**Labels:**
Issue, Enhancement

**Comment by RAOdotSH** [comment]
If you got any issues or find the idea unclear, please contact me on Discord (PRO7ON#1609).
Thank You.

**Comment by sahil-sagwekar2652** [comment]
How would this solution benefit this particular project? Can you please explain?

**Comment by RAOdotSH** [comment]
- If a competition want to be held where each participant requires his/her individual repo to push into then instead of creating it manually we can just run the script. 
- It will add the respected contributors to the repo.
- It also has support for a template repo, means it will create a copy of given repo in our organization.
