### ISSUE TITLE
Fork and clone a repo

### ISSUE THREAD

**Issue by GayathriManeksha** [sahil-sagwekar2652/GitHub-Automation-scripts#95]
**Issue Description:**
A script to fork and clone a repo

**Expected Behavior:**
The script will have the code to fork a repository and then clone to it.

**Labels:**
Enhancement

**Comment by GayathriManeksha** [comment]
Please assign this issue to me as part of gssoc23

**Comment by bhavika2502** [comment]
I would like to work on this issue as I have experience in Python and Github API as part of gssoc23

**Comment by aryasoni98** [comment]
I would like to work on this issue .

**Comment by AaryaZ** [comment]
@sahil-sagwekar2652 I have understood the issue and would like to work on it.

**Comment by GayathriManeksha** [comment]
@sahil-sagwekar2652 Can you assign this to me as part of gssoc'23

**Comment by srivatsavsurya** [comment]
I can do this
